title: Simple string formatting in Python
hero_image: images/banner.png
description: Formatting strings in Python
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: "python"
site_areas:
steps:
  - title: String formatting

