---
title: पायथन में सरल स्ट्रिंग प्रारूपण
hero_image: images/banner.png
description: पायथन में स्ट्रिंग्स का प्रारूपण
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - title: स्ट्रिंग प्रारूपण

